/**
 * Generates Projects component.
 * @return Component
 */
const Projects=()=>{const e=document.createElement('div');e.setAttribute('id','Projects');const e0=document.createElement('h3');e0.textContent=`simple-wm`;e.appendChild(e0);const e1=document.createElement('p');e1.textContent=`A dynamic window manager, heavily inspired on dwm.`;e.appendChild(e1);const e2=document.createElement('p');e2.textContent=`The goal is provide the same experience of dwm, but with better code (both in terms of performance and readability).`;e.appendChild(e2);const e3=document.createElement('a');e3.setAttribute('href','https://github.com/miguelrcborges/simple-wm');e3.textContent=`Repo`;e.appendChild(e3);const e4=document.createElement('br');e.appendChild(e4);const e5=document.createElement('br');e.appendChild(e5);const e6=document.createElement('h3');e6.textContent=`html2js`;e.appendChild(e6);const e7=document.createElement('p');e7.textContent=`A simple html to javascript compiler, which would be considerably similar to frameworks that use JSX.`;e.appendChild(e7);const e8=document.createElement('p');e8.textContent=`The goal is to provide a zero-cost abstraction that automates elements generation, which can be easily used with vanilla javascript.`;e.appendChild(e8);const e9=document.createElement('p');e9.textContent=`This site uses html2js to generate each section.`;e.appendChild(e9);const e10=document.createElement('a');e10.setAttribute('href','https://github.com/miguelrcborges/html2js');e10.textContent=`Repo`;e.appendChild(e10);return e;};
/**
 * Generates Connections component.
 * @return Component
 */
const Connections=()=>{const e=document.createElement('div');e.setAttribute('id','Connections');const e0=document.createElement('ul');const e1=document.createElement('li');const e2=document.createElement('a');e2.setAttribute('href','https://blog.miguelrcborges.rocks');e2.textContent=`Blog`;e1.appendChild(e2);e0.appendChild(e1);const e3=document.createElement('li');const e4=document.createElement('a');e4.setAttribute('href','https://github.com/miguelrcborges');e4.textContent=`Github`;e3.appendChild(e4);e0.appendChild(e3);e.appendChild(e0);return e;};
/**
 * Generates Info component.
 * @return Component
 */
const Info=()=>{const e=document.createElement('div');e.setAttribute('id','Info');const e0=document.createElement('p');e0.textContent=`General Info`;e.appendChild(e0);const e1=document.createElement('ul');const e2=document.createElement('li');e2.textContent=`Name: Miguel Rodrigues Carrilho Borges`;e1.appendChild(e2);const e3=document.createElement('li');e3.textContent=`Birth Date: 8 Feb 2002`;e1.appendChild(e3);const e4=document.createElement('li');e4.textContent=`Pronouns: He/Him`;e1.appendChild(e4);const e5=document.createElement('li');e5.textContent=`Favourite programming languages: C, Go`;e1.appendChild(e5);const e6=document.createElement('li');e6.textContent=`Interests: Signal Processing, Robotics, Compilers, Neurology`;e1.appendChild(e6);e.appendChild(e1);return e;};
